'use strict'

// Re-export all constants for backward compatibility

// From tags.ts
export { FALSE, TRUE } from './tags'
export { OPERATION_ATTRIBUTES_TAG, JOB_ATTRIBUTES_TAG, END_OF_ATTRIBUTES_TAG, PRINTER_ATTRIBUTES_TAG, UNSUPPORTED_ATTRIBUTES_TAG } from './tags'
export { UNSUPPORTED, UNKNOWN, NO_VALUE } from './tags'
export { INTEGER, BOOLEAN, ENUM } from './tags'
export { OCTET_STRING, DATE_TIME, RESOLUTION, RANGE_OF_INTEGER, TEXT_WITH_LANG, NAME_WITH_LANG } from './tags'
export { TEXT_WITHOUT_LANG, NAME_WITHOUT_LANG, KEYWORD, URI, URI_SCHEME, CHARSET, NATURAL_LANG, MIME_MEDIA_TYPE } from './tags'

// From operation-ids.ts
export { PRINT_JOB, PRINT_URI, VALIDATE_JOB, CREATE_JOB, SEND_DOCUMENT, SEND_URI, CANCEL_JOB, GET_JOB_ATTRIBUTES, GET_JOBS, GET_PRINTER_ATTRIBUTES, HOLD_JOB, RELEASE_JOB, RESTART_JOB, PAUSE_PRINTER, RESUME_PRINTER, PURGE_JOBS } from './operation-ids'

// From status-codes.ts
export { SUCCESSFUL_OK, SUCCESSFUL_OK_IGNORED_OR_SUBSTITUTED_ATTRIBUTES, SUCCESSFUL_OK_CONFLICTING_ATTRIBUTES } from './status-codes'
export { CLIENT_ERROR_BAD_REQUEST, CLIENT_ERROR_FORBIDDEN, CLIENT_ERROR_NOT_AUTHENTICATED, CLIENT_ERROR_NOT_AUTHORIZED, CLIENT_ERROR_NOT_POSSIBLE, CLIENT_ERROR_TIMEOUT, CLIENT_ERROR_NOT_FOUND, CLIENT_ERROR_GONE, CLIENT_ERROR_REQUEST_ENTITY_TOO_LARGE, CLIENT_ERROR_REQUEST_VALUE_TOO_LONG, CLIENT_ERROR_DOCUMENT_FORMAT_NOT_SUPPORTED, CLIENT_ERROR_ATTRIBUTES_OR_VALUES_NOT_SUPPORTED, CLIENT_ERROR_URI_SCHEME_NOT_SUPPORTED, CLIENT_ERROR_CHARSET_NOT_SUPPORTED, CLIENT_ERROR_CONFLICTING_ATTRIBUTES, CLIENT_ERROR_COMPRESSION_NOT_SUPPORTED, CLIENT_ERROR_COMPRESSION_ERROR, CLIENT_ERROR_DOCUMENT_FORMAT_ERROR, CLIENT_ERROR_DOCUMENT_ACCESS_ERROR } from './status-codes'
export { SERVER_ERROR_INTERNAL_ERROR, SERVER_ERROR_OPERATION_NOT_SUPPORTED, SERVER_ERROR_SERVICE_UNAVAILABLE, SERVER_ERROR_VERSION_NOT_SUPPORTED, SERVER_ERROR_DEVICE_ERROR, SERVER_ERROR_TEMPORARY_ERROR, SERVER_ERROR_NOT_ACCEPTING_JOBS, SERVER_ERROR_BUSY, SERVER_ERROR_JOB_CANCELED, SERVER_ERROR_MULTIPLE_DOCUMENT_JOBS_NOT_SUPPORTED } from './status-codes'

// From states.ts
export { PRINTER_IDLE, PRINTER_PROCESSING, PRINTER_STOPPED } from './states'
export { JOB_PENDING, JOB_PENDING_HELD, JOB_PROCESSING, JOB_PROCESSING_STOPPED, JOB_CANCELED, JOB_ABORTED, JOB_COMPLETED } from './states'
